all:
	@g++ -std=gnu++11 -g bt.cpp -Wall -Werror -o bt && ./bt -d program.bin && echo ''

build:
	@g++ -std=gnu++11 -g bt.cpp -Wall -Werror -o bt && echo ''

preprocess:
	@g++ -std=gnu++11 -E bt.cpp && echo ''

clean:
	@rm -rf *.o bt