all:
	@g++ -std=gnu++11 -g bt.cpp -Wparentheses -Wunused-value -Wformat -o bt && ./bt && echo ''

build:
	@g++ -std=gnu++11 -g bt.cpp -Wparentheses -Wunused-value -Wformat -o bt && echo ''

clean:
	@rm -rf *.o bt