all:
	@g++ -std=gnu++11 -g b2h.cpp -o ../../bin/bin2hex -Wparentheses -Wunused-value -Wformat && ../bin2hex && echo ''

build:
	@g++ -std=gnu++11 -g b2h.cpp -o ../../bin/bin2hex -Wparentheses -Wunused-value -Wformat && echo ''

clean:
	@rm -rf *.o ../bin2hex